---
title: "Black Lives Matter (Main Page)"
description: P.S. this website isn't broken it's just old school cool
author: "Revilla"
date: "01/01/9999"
output: html_document
categories:
  - Black Lives Matter
tags:
  - index
---
# Here's an in-depth set of info related to Black Lives Matter for Canadians<br><br>

### Beginner Resources If You Feel Overwhelmed

* [Systemic Racism Explained (Video 4:23 length)](https://www.youtube.com/watch?v=YrHIQIO_bdQ)<br>

* [How to ACTUALLY Stop Police Brutality (Video 11:31 length)](https://www.youtube.com/watch?v=2JGMB7hIO5A)<br>
* [Free #DoTheWork 30 Day Course by Rachel Cargle (via email)](http://eepurl.com/dzbN9f)<br>
* [Antiracism Resources for White People (Google Doc)](https://bit.ly/antiracismresources)<br>
* [How to Be an Antiracist
by Ibram X. Kendi (Book)](https://www.goodreads.com/book/show/40265832-how-to-be-an-antiracist)<br>

* [A History of Slavery in the United States (Interactive Timeline by National Geographic)](https://www.nationalgeographic.org/interactive/slavery-united-states/)


### Educational Tools

* [Documentaries](/blm/documentaries/)<br><br>
* [Podcasts](/blm/podcasts/)<br><br>
* [Influencers](/blm/influencers/)<br><br>
* [Books](/blm/books/)<br><br>
* [Websites](/blm/websites/)<br><br>
* [Data](/blm/data/)<br><br>

### Local Black Businesses & Institutions
* [Calgary](/blm/calgary/)<br><br>
* [Vancouver](/blm/vancouver/)<br><br>

### Places to Donate

* [Split a donation between 70+ community bail funds, mutual aid funds, and racial justice organizers](https://secure.actblue.com/donate/bail_funds_george_floyd)<br>

* [Support orgs fighting for racial justice](https://secure.actblue.com/donate/ab_mn)<br>

* [Support the Protest & COVID-19 Emergency Response Fund for Community Bail & Bond Funds!](https://secure.actblue.com/donate/bailfundscovid)<br>

* [115 Ways to Donate in Support of Black Lives and Communities of Color](https://nymag.com/strategist/article/where-to-donate-for-black-lives-matter.html)<br>


* []()<br><br>

